spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?serverTimezone=UTC
    username: root
    password: dkssud3857!
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true

logging:
  level:
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
